// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-13 10:07:05.294455 +0800 CST m=+0.714540738

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Exchange server API 1.0 swagger doc",
        "title": "Exchange server API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/order_books": {
            "get": {
                "description": "get your order book list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "order book list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "eg BTC_USD",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderBook"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create an order book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "new an order book",
                "parameters": [
                    {
                        "description": "order book form",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/forms.OrderBookForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/dtos.OrderBookDTO"
                        }
                    }
                }
            }
        },
        "/order_books/{id}": {
            "put": {
                "description": "update an exist order book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "update an order book",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "eg 1",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "order book model",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.OrderBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.OrderBook"
                        }
                    }
                }
            },
            "delete": {
                "description": "cancel an exist order book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "cancel an order book",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "eg 1",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.APIRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.OrderBookDTO": {
            "type": "object",
            "properties": {
                "fund_id": {
                    "type": "integer"
                },
                "order_type": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "side": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "forms.OrderBookForm": {
            "type": "object",
            "properties": {
                "order_type": {
                    "description": "market or limit",
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "side": {
                    "description": "sell or buy",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "models.Currency": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deposit_fee": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "withdraw_fee": {
                    "type": "number"
                }
            }
        },
        "models.Fund": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "leftCurrency": {
                    "type": "object",
                    "$ref": "#/definitions/models.Currency"
                },
                "leftCurrencyID": {
                    "type": "integer"
                },
                "limit_rate": {
                    "type": "number"
                },
                "market_rate": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "rightCurrency": {
                    "type": "object",
                    "$ref": "#/definitions/models.Currency"
                },
                "rightCurrencyID": {
                    "type": "integer"
                },
                "symbol": {
                    "description": "eg btc_usd eth_usd",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.OrderBook": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "fund": {
                    "type": "object",
                    "$ref": "#/definitions/models.Fund"
                },
                "fund_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "order_type": {
                    "description": "market or limit",
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "side": {
                    "description": "sell or buy",
                    "type": "string"
                },
                "status": {
                    "description": "pending done cancel reject",
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/models.User"
                },
                "user_id": {
                    "type": "integer"
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "utils.APIRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
